# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-27 20:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20160825_1834'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billingdetails',
            name='user',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='user',
        ),
        migrations.AddField(
            model_name='billingdetails',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='billingdetails',
            name='first_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='billingdetails',
            name='last_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='billing_details',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.BillingDetails'),
        ),
    ]
